### ISSUE TITLE
Troubleshooting login

### ISSUE THREAD

**Issue by znck** [znck/grammarly#315]
### Discussed in https://github.com/znck/grammarly/discussions/296

<div type='discussions-op-text'>

<sup>Originally posted by **BoDonkey** July 15, 2022</sup>
Hi,
I'm using Grammarly desktop with a premium subscription. When I connect to Grammarly through the command palette, it opens a browser window and seemingly connects. However, the icon at the bottom turns red and states that there is a connection error. There isn't anything special in the output section. Any pointers on troubleshooting this?
Thanks</div>

**Comment by InTEGr8or** [comment]
I am having the same error and getting this message at Grammarly: https://vscode-extension-grammarly.netlify.app/.netlify/functions/redirect?code=<long_code>

<img width="374" alt="image" src="https://user-images.githubusercontent.com/1802850/186959026-68df7d59-dcae-44b8-859b-fb28ec1302c9.png">

**Comment by michidk** [comment]
The URL actually looks like this: [vscode-extension-grammarly.netlify.app/.netlify/functions/redirect?code=](https://vscode-extension-grammarly.netlify.app/.netlify/functions/redirect?code=<long_code>&state=<base64url>
As a workaround, you can copy the `code` and `state` parameters from the URL. Decode the state value (for example with https://www.base64decode.org/), which should be a URL. Add the &code=<long_code> to the URL you just decoded and visit that URL in your browser.

For me the decode state value hat the following value: vscode://znck.grammarly/auth/callback?windowId=1
So I added the code value that it looks like this: vscode://znck.grammarly/auth/callback?windowId=1&code=4UNI78423QHtdh....

After visiting it, vscode said "Account connected.".

**Comment by abbreviatedman** [comment]
Can confirm the above workaround (quoted below).

To clarify:

1.  Select &ldquo;Grammarly Login&rdquo; from the Command Palette.
2.  Go to the URL it gives you and authorize the application.
3.  When you get Netlify&rsquo;s Page Not Found error, copy the URL you&rsquo;re currently visiting.
4.  Take the part after \`&state=\` and run it through a base64 decoder, like the one at <https://www.base64decode.org/>. For me, like the author above, it gave me &ldquo;vscode://znck.grammarly/auth/callback?windowId=1&rdquo;, which is likely what it gave you as well. If that&rsquo;s true for everyone, we may be able to skip this step and simply use the &ldquo;vscode://&rdquo; URL for the following step.
5.  Take the URL from step 4, append \`&code=\` and the end of the original URL—the part *after* \`?code=\`.
6.  Go to that URL and it should log you in.

> The URL actually looks like this: `https://vscode-extension-grammarly.netlify.app/.netlify/functions/redirect?code=<long_code>&state=<base64url>` As a workaround, you can copy the `code` and `state` parameters from the URL. Decode the state value (for example with <https://www.base64decode.org/>), which should result in a URL. Add the &code= to the URL you just decoded and visit that URL in your browser.
>
> For me the decode state value hat the following value: `vscode://znck.grammarly/auth/callback?windowId=1` So I added the code value that it looks like this: `vscode://znck.grammarly/auth/callback?windowId=1&code=4UNI78423QHtdh...`
>
> After visiting it from Firefox, vscode said &ldquo;Account connected.&rdquo;.

**Comment by pati-ni** [comment]
The workarounds do not work for me! Instead of a proper redirection I get this error:

![redirect URI](https://user-images.githubusercontent.com/14965608/187708552-5386d148-b49c-458a-8485-59d2188216af.png)

**Comment by TcNobo** [comment]
This is a rather annoying little bug, and I've just run across it trying this extension for the first time. Was about to give up. The fix worked, although took a second to figure out.

**Comment by rudeigerc** [comment]
It seems like Netlify Functions is not configured properly. The [documentation](https://docs.netlify.com/functions/build/?fn-language=ts) shows that the default functions directory is `YOUR_BASE_DIRECTORY/netlify/functions`, which does not meet the current file structure. Since only the maintainers could maintain the configuration on Netlify, I'm unsure whether it is related to the issue. Could someone have a look at it?

**Comment by znck** [comment]
Fixed https://github.com/znck/grammarly/commit/383ae96b69fec578e30fe91e1cd35ce62d8243ae. And configured to deploy from CI.

**Comment by frederikprijck** [comment]
Not sure this belongs here, happy to open another issue if needed. 

I just installed the extension for the very first time, was able to login successfully (browser opened, code exchange happened and the extension said "Account connected"), but then it gives me the red icon in the bottom right saying: `Connection status: error`.

**Comment by dudarboh** [comment]
I still experienced the same issue with logging in and it took me two hours to make it work, but this thread helped a lot.

1. Trying to log in via `https://vscode-extension-grammarly.netlify.app/.netlify/functions/redirect` didn't work and resulted in the firefox error message : "vscode-extension-grammarly.netlify.app the address wasn't understood"

2. Trying to use `vscode://znck.grammarly/auth/callback?windowId=1` didn't work, as firefox couldn't execute the link and was always googling it.

3. Using this in terminal finally worked for me
```
code --open-url "vscode://znck.grammarly/auth/callback?windowId=1&code=..."
```

OS: Ubuntu 22:04/03
Browser: Firefox 120.0 (x64)
VSCode appimage details:
          Version: 1.84.2
          Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
          Date: 2023-11-09T10:50:47.800Z
          Electron: 25.9.2
          ElectronBuildId: 24603566
          Chromium: 114.0.5735.289
          Node.js: 18.15.0
          V8: 11.4.183.29-electron.0
          OS: Linux x64 5.15.0-88-generic
Grammarly extension: v0.25.0
